--- 
- name: download jenkins
  ansible.builtin.get_url:
        url: "{{ jenkins_url }}"
        dest: "{{ tomcat_latest }}/webapps/{{ jankins_username }}"
        owner: "{{ username }}"
        group: "{{ username }}"
  notify:
        - start, enable and reload the tomcat service  