---
# tasks file for commen
 - include_tasks: update.yaml
   when: ansible_facts['os_family'] == "Debian"
 - include_tasks: java.yaml
 - include_tasks: tomcat.yaml
 - include_tasks: app-deploy.yaml
    