- name: copy the tomcat service files
  ansible.builtin.template:
        src: 'tomcat.service.j2'
        dest: "{{ tomcat_service_file }}"
        owner: "{{ username }}"
        group: "{{ username }}"
  notify:
        - start, enable and reload the tomcat service
- name: Ensure the tomcat service start
  ansible.builtin.systemd:
        name: 'tomcat.service'
        state: 'started' 
- name: create the tomcat user file
  ansible.builtin.template:
        src: 'tomcat-user.xml.j2'
        dest: "{{ tomcat_latest }}/{{ tomcat_user_xml_file }}"
        owner: "{{ username }}"
        group: "{{ username }}"
  notify:
        - start, enable and reload the tomcat service 
- name: tomcat access the hostmanager and manager 
  ansible.builtin.template:
        src: 'manger-context.xml.j2'
        dest: "{{ item }}"
        owner: "{{ username }}"
        group: "{{ username }}"
  loop: "{{ tomcat_user_acces_anywhere }}"
  notify:
        - start, enable and reload the tomcat service